### ISSUE TITLE
self-locating PSUtils.cpm

### ISSUE THREAD

**Issue by kberry** [rrthomas/psutils#17]
unless i'm missing something, in psutils 1.90, the scripts can't be used in TeX Live as is, since they "use PSutils" but do nothing to add a relative directory to the search path. Since TL can be installed anywhere, it would be necessary to do something like unshift(@INC, $psutilsdir)
where $psutilsdir is given by $FindBin::RealBin. wdyt?

In addition, it is unclear to me whether we can reasonably install your new paper program in TL, unless distros have generally adopted it. Making this scheme interoperate with TL's paper selection does not look simple. So maybe it is not worth doing anything, and we simply will not ever upgrade psutils, or leave it to the distros ... --best, karl.

**Comment by rrthomas** [comment]
I did some work on relocatable-perl for gnulib some years ago, I will have a look to see if I can use that.

Paper is intended to replace Debian's libpaper, so you could wait and see if I can persuade Debian.

Note that psutils works without paper (or if it doesn't, that's a bug). However, paper is the only way to specify paper sizes. I would like to know about problems with interoperation (do file an issue against paper!). In particular, what's the problem with setting the environment variable `PAPERSIZE`?

**Comment by kberry** [comment]
we don't want to force users to set an environment variable (surely no distro does either). There is a standard mechanism for users to set their paper size for all the programs that care, which edits the relevant configuration files. For psutils, that was <tlroot>/texmf-dist/paper.cfg in the last release (probably we overrode it somehow, I don't know).

Anyway, yes, will await results with Debian.

**Comment by rrthomas** [comment]
I'm a bit baffled: I used an environment variable because it's an easy and universally-supported way for a user to express a preference. If I'm wrong about that, I could also add a configuration file (although that immediately adds the problem of where to put it; but hey, other programs solve that). Also note that the default paper size for the user's locale is automatically obtained on systems that support that.

I also imagined that systems with their own paper configuration mechanisms (such as TeXLive) would simply set the environment variable…is that not possible? Surely TeXLive sets other environment variables?

**Comment by kberry** [comment]
TL does not set, or require, any environment variables.

**Comment by norbusan** [comment]
Two remarks: allowing users to override some system setting using env vars is fine, but the default should be defined via a configuration file and **not** via an env var.

I am sure that Debian will not do anything now as they are in deep freeze before release of buster.

Whether/How psutils new versions are adapted depends on the maintainer, who is Ian Jackson. Do to personal reasons I will never contact him for whatever reason - he start a witch hunt on me. Currently there is version 1.17 of psutils in Debian.

For TeX Live - I would say if it is not self-relocatable and cannot be customized via a configuration file then we should consider removing it from TL, as it simply will not work, which is much worse than having no psutils as an installed TL would shadow the system psutils which might work.

**Comment by rrthomas** [comment]
Thanks both for your help. I will implement a configuration file and relocatability (after all, I( wrote the gnulib support for that!).

I get on fine with Ian, so I'll see what happens after the Buster freeze is lifted.

The idea with removing the configuration file altogether is that the default is the locale default, but I admit that implementations are need for non-glibc systems before that could be considered a universal solution! So, I shall add a per-user config file for the paper size.
