### ISSUE TITLE
psutils is broken if LANG is set de_DE.UTF8

### ISSUE THREAD

**Issue by fjaell** [rrthomas/psutils#18]
I got lots of error like the following with the test-suite if I set LANG:

$:> export LANG=de_DE.UTF8
$:> psnup
bad dimension at /usr/lib/perl5/site_perl/5.28/PSUtils.pm line 34.

**Comment by rrthomas** [comment]
Thanks very much for this report. I'm pretty sure I know what the problem is, and the fix; will look as soon as I can find a moment.

**Comment by rrthomas** [comment]
This should be fixed now (I have pushed a tested fix, which involves setting the locale to C when using POSIX::strtod).

Do let me know if the problem persists for you!

**Comment by fjaell** [comment]
Yeah, works for me. Many thanks :)

**Comment by rrthomas** [comment]
Great, thanks for letting me know!
