### ISSUE TITLE
pstops pagespec parsing bugs

### ISSUE THREAD

**Issue by perropelao** [rrthomas/psutils#19]
It seems that pstops shift is not working. A command like
```
pstop '1:0(100pt,100pt)' file1.ps > file2.ps
```
produces a ps that is visually the same with no content shifted.

I have reproduced the problem with the pstops of my distro (Manjaro, psutils 1.90-1), and with the code in the master branch. 

Nevertheless, [1.23](https://github.com/rrthomas/psutils/releases/tag/v1.23) works properly.

**Comment by rrthomas** [comment]
Thanks for the report; I can confirm the bug. I am working on a fix.

**Comment by rrthomas** [comment]
I will make a new release shortly.

**Comment by perropelao** [comment]
Thank you very much for your fast response.
I think there is still a problem with negative numbers. Version 1.23 allowed negative shifts. But it seems that your regular expression doesn't allow a sign. And, in fact, after recompiling 1.91, I have checked that specs with negative shifts are ignored.
I think there is another error, not related with shifting but with specs separated with ",". It seems that they are dropped and don't contribute to a new page.
Should I report these problems as new issues?

**Comment by rrthomas** [comment]
Thanks, and sorry, I'll look into this.

**Comment by rrthomas** [comment]
Should now be fixed, and tests added (issue #15).

**Comment by perropelao** [comment]
Thanks again.
One more observation. Version 1.23 allows rotations with multiple letters (i.e. LLL) and composes them to produce the equivalent rotation (LLL = R). But 1.9x ignores specs with multi-letter rotations. For me it is no problem, because I have updated my scripts from LLL to R. But I wonder if you have removed this feature on purpose or if it never was a feature but a *side effect*.

**Comment by rrthomas** [comment]
This was an unintentional change by me, but as far as I can see it was only ever a side-effect of the way the pagespecs parser was implemented. In particular, I don't believe I've changed the documented syntax. Looking at the 1.17 man page, it says:

    spec        = [-]pageno[L][R][U][H][V][@scale][(xoff,yoff)]

I have made `L`, `R` and `U` mutually exclusive, because I believe that's the intention, and similarly with `H` and `V`, but it doesn't suggest that you can use each more than once (I must admit, it never occurred to me!).

Having thought about it, I think I can implement this (and perhaps even more importantly, document it) quite simply, and so I will give it a go. Thanks again.

**Comment by rrthomas** [comment]
I would change the syntax to

    turn = L|R|U|H|V
    turn = turn[turns]
    spec = [-]pageno[turns][@scale][(xoff,yoff)]

and document turns as follows: where the man page pstops(1) currently says "The optional parameters", it will say: "Turns are applied in sequence."

How does that sound?

**Comment by perropelao** [comment]
Sounds good. I think it makes easier to implement tools that generate specs.

I suppose you mean:
```
turns = turn[turns]
```
don't you?

Thanks for all these improvements. And, of course, for all these ps utils. I have been using them for many years with great satisfaction.

**Comment by rrthomas** [comment]
Thanks for the fix. And of course I didn't write psutils, I merely rewrote them to save them for the future!

**Comment by rrthomas** [comment]
Functionality added in commit 1e7f302.
