### ISSUE TITLE
psmerge question

### ISSUE THREAD

**Issue by za3k** [rrthomas/psutils#23]
Sorry to ask a question in the bug report section.

Why is 'psmerge' marked as obsolete and no longer included? Could be useful to add a comment to the top of the file.

Edit: Is this because psjoin is redundant? I didn't notice that alternative

**Comment by rrthomas** [comment]
Yes, I believe psjoin can be used instead, and if true merging is required it's probably dependent on the use case and one is better off using gs directly.
