### ISSUE TITLE
Configure-time support for libpaper

### ISSUE THREAD

**Issue by za3k** [rrthomas/psutils#26]
Would you be up to add a configure-time option to use 'libpaper''s 'paperconf' in place of 'paper'? I don't see a huge difference between the two, and while 'libpaper' is packaged on my distro (arch), I'd have to add a new package for 'paper'.

I can (and probably will) do that but I just know a program called 'paper' is someday going to conflict with other packages, and I've never seen it used elsewhere.
Edit: I did add a package to arch linux but I still think this is a good idea

**Comment by rrthomas** [comment]
paper replaces libpaper.

**Comment by rrthomas** [comment]
(Note however for packaging: paper can coexist with libpaper.)
