### ISSUE TITLE
Data are lost between execs when using pipes

### ISSUE THREAD

**Issue by bwhissel** [rrthomas/psutils#29]
I commented on Issue #25 which had been closed, but it didn't look like I could re-open it. Like Issue #25, I also had trouble using the psutils in a filter chain, using the most recent version from GitHub here. To create a folded booklet from double-sided 2-up pages, my chain looks like:
```
dvips -f book | psbook | psnup -2 > out.ps`
```
I think I tracked down the problem to the `seekable()` function in `PSUtils.pm`. After STDIN has been copied to the temporary file, the `$fp` handle is closed, closing STDIN, and the tempfile's file handle is returned in its place.

The problem is that in the calling function `setup_input_and_output()`, we have `$infile = seekable($infile)`. This replaces the reference to STDIN with the new filehandle, but the file descriptor associated with STDIN has already been closed. Since the next process `psselect` is exec'd and STDIN has been closed, the next process has no open STDIN descriptor.

One way to fix this may be to _reopen_ STDIN using the new file descriptor, rather than simply closing it. E.g., in `seekable()`, replace
```
close $fp;
return $ft if seek $ft, 0, SEEK_SET;
```
with something like
```
open($fp, "<&=", fileno($ft));
return $fp if seek $fp, 0, SEEK_SET;
```
This replaces STDIN itself with the open file descriptor pointing to the tempfile, and this value is preserved across the exec.

**Comment by rrthomas** [comment]
@bwhissel: thanks for your reports, and especially for the suggested fixes. I'm looking into them and will make a new release as soon as I can.

**Comment by bwhissel** [comment]
Thank you. And a special thanks for maintaining these utilities! I've been using them for years.

**Comment by rrthomas** [comment]
I made one small change to your suggested fix: it's not necessary to call `fileno` on the handle, as `open` does that automatically.

**Comment by bwhissel** [comment]
Ah, nice. And good to know for the future. Thanks for the fix!
