### ISSUE TITLE
we didn't have full codes here, right?

### ISSUE THREAD

**Issue by ghiewa** [rrthomas/psutils#3]

**Comment by rrthomas** [comment]
I'm sorry, I don't understand the question, unless you mean "is the full code of psutils here?" in which case the answer is: yes, the full code is here.

**Comment by ghiewa** [comment]
exp, there is no config.h. 

It is need time read through all your coding ：）

**Comment by rrthomas** [comment]
`config.h` is generated by `bootstrap`. This is documented in `README`. Please file an issue if something is unclear or missing.

**Comment by ghiewa** [comment]
well, exceed my knowledge, and seems you are not willing transfer it to win os, as a take away tool.

**Comment by rrthomas** [comment]
psutils is portable. There is no reason why it shouldn't work on Windows; if it doesn't, that is a bug; although it will need a GNU build environment (such as MSYS2 or MingW64).

If by "take away tool" you mean a Windows installer, then that is correct, I don't have time to provide that, but someone else is welcome to. In a similar way, I don't provide installers for GNU/Linux or macOS, but I rely instead on other people, and psutils is available in many GNU/Linux distributions and in brew for macOS. It is available in GnuWin for Windows, and it should also be straightforward to package directly for e.g. Chocolatey.

But there are thousands of OSes and package systems, so sorry, but I don't have time to provide for even 10!

**Comment by ghiewa** [comment]
yes, by using babun/cgywin, I finially get pstops on win os. thanks for your hard work.

**Comment by rrthomas** [comment]
I will update the README to try to address the question of finding pre-compiled versions. Thank you very much for your input.
