### ISSUE TITLE
psnup does not respect output paper size

### ISSUE THREAD

**Issue by fdservices** [rrthomas/psutils#31]
Converting a postscript file using psnup always outputs in letter size.
To reproduce take a four A4 page postscript file and convert it to booklet page order

psbook printfile.ps psbook.ps

Convert the pages to two up

psnup -p A4 -2 psbook.ps fpbooklet.ps

The result is a booklet file on Letter format.

**Comment by rrthomas** [comment]
What version of psutils is this? Your example works fine for me with the most recent version, 2.04 (and it should work in any 2.xx version). There's a (passing) test for setting a non-default output paper size in the current version. I also checked outputting Letter size paper, since A4 is the default on my system.

**Comment by fdservices** [comment]
I am using psutils 2.03 running on Arch linux 5.9.9. My default paper size is also A4

**Comment by fdservices** [comment]
There is an error reported from pstops:

$ psbook printfile.ps psbook.ps
[1] [2] [3] [4] Wrote 4 pages
$ psnup -p A4 -2 psbook.ps fpbooklet.ps
Use of uninitialized value $upto in subtraction (-) at /usr/bin/pstops line 277, <STDIN> line 12554.
[1] [2] Wrote 2 pages

**Comment by fdservices** [comment]
Could not attach the postscript file so:
$ pdf2ps printfile.pdf

[printfile.pdf](https://github.com/rrthomas/psutils/files/5577244/printfile.pdf)

**Comment by rrthomas** [comment]
Nice choice of file! That particular error is fixed by 2.04, and I confirm that using your attached `printfile.pdf` with `pdf2ps` and then running your test, I get A4 output.

I also tried running the test with 2.03. I get the same error as you do (I believe it's harmless by the way), and I again get A4 output.

**Comment by rrthomas** [comment]
I tried changing my default paper size to Letter, and ran the test, and again I get A4 output. I'm sorry, I'm running out of ideas here.

**Comment by rrthomas** [comment]
You can attach your original PostScript file by adding the suffix `.txt`. Could you please attach that and your `fpbooklet.ps` file?

**Comment by fdservices** [comment]
Something is strange here. I attached the file "printfile.pdf". It is a text file from the psnup man page, printed in pdf format.

Here are all the files used, having converted printfile.pdf to printfile.ps, in .zip format:
[psnup.zip](https://github.com/rrthomas/psutils/files/5577718/psnup.zip)

**Comment by rrthomas** [comment]
Thanks. fpbooklet.ps in your Zip file is A4 format.

**Comment by fdservices** [comment]
I really do appreciate your time on this!
If I look at the file using ghostscript I get:
![ghostscript](https://user-images.githubusercontent.com/3006039/99879005-b3ee5180-2c09-11eb-98dc-b871043c55ab.png)
If I convert the file to pdf using ps2pdf I get:
[fpbooklet.pdf](https://github.com/rrthomas/psutils/files/5577731/fpbooklet.pdf)
I have no idea what is going wrong?

**Comment by rrthomas** [comment]
If I open fpbooklet.ps in gs (I was using evince before), it displays normally. (I'm using GhostScript 9.50 as supplied with Ubuntu 20.04.) Anyway, the DocumentMedia and BoundingBox lines say:

```
%%DocumentMedia: plain 595 842 0 () ()
%%BoundingBox: 0 0 595 842
```

which are A4 (divide by 72 and multiply by 2.54!).

The obvious thing that comes to mind is the default paper size configured for your installation of GhostScript; in any case, the output of psutils is clearly correct, so I'm closing the bug. I suggest you add "-sPAPERSIZE=a4" to your invocation of ps2pdf.

**Comment by fdservices** [comment]
Thank you for your help and I apologize for my ignorance. :)

**Comment by rrthomas** [comment]
No problem! It turns out that Debian's ghostscript (and hence Ubuntu's) uses libpaper, so it respects the default system paper size. I guess Arch doesn't do that. You can however set ghostscript's default paper size in `gs_init.ps`.

**Comment by rrthomas** [comment]
Alternatively, you've not configured libpaper's default paper size?

**Comment by fdservices** [comment]
Thanks - may be not quite so stupid :)

**Comment by fdservices** [comment]
Absolutely right. "paper" is set correctly. May be paper should also let libpaper?

**Comment by rrthomas** [comment]
Thereby hangs a tale! Paper is designed as a replacement for libpaper, and I'm trying to work out how to get there…

**Comment by fdservices** [comment]
I suppose you would not consider a rewrite of ghostscript while you are at it? :) :) :)

**Comment by rrthomas** [comment]
The idea is to have ghostscript use the new libpaper, indeed.
