### ISSUE TITLE
Incorrect mediasize with psresize

### ISSUE THREAD

**Issue by saumyakswain** [rrthomas/psutils#32]
psresize does not change to mediasize
I'm not sure whether that is the intended behavior. Could not find any clear docs, so filing an issue.
I'm trying to resize an a1 document to a4 with psresize. While the output is scaled, the DocumentMedia is unchanged as a result I get a cropped output when viewing on evince.

Version Used:
psresize release 1 patchlevel 17  (Ubuntu bionic default) and
psresize 2.04 latest github release

Resize command:
psresize -PA1 -pa4 test.ps test1.ps

Header of original file:
%!PS-Adobe-2.0
%%Creator: dvips(k) 5.999 Copyright 2019 Radical Eye Software
%%Title: test.dvi
%%CreationDate: Wed Mar 31 10:38:44 2021
%%Pages: 1
%%PageOrder: Ascend
%%BoundingBox: 0 0 1684 2384
%%DocumentFonts: CMBX12 CMR10 CMTI10
%%DocumentPaperSizes: a1
%%EndComments

Header of resized file
%!PS-Adobe-2.0
%%Creator: dvips(k) 5.999 Copyright 2019 Radical Eye Software
%%Title: test.dvi
%%CreationDate: Wed Mar 31 10:38:44 2021
%%DocumentMedia: plain 1684 2382 0 () ()
%%BoundingBox: 0 0 1684 2382
%%Pages: 1 0
%%PageOrder: Ascend
%%DocumentFonts: CMBX12 CMR10 CMTI10
%%EndComments

Expected Behavior:
The resized/output file should have %%DocumentMedia properties of a4 paper and not of a1 paper.

Solution:
Manually editing the %%DocumentMedia: to "A4 595 842 0 () ()" solves the problem. I've almost no idea on ps specs so please excuse me if this is intentional or something like that.

**Comment by rrthomas** [comment]
With psutils 2.04:

```
$ echo 1 | a2ps --medium=A3 --lines-per-page=4 --portrait --columns=1 --rows=1 --no-header --output=a3.ps
[stdin (plain): 1 page on 1 sheet]
[Total: 1 page on 1 sheet] saved into the file `a3.ps'
$ psresize -PA3 -pa4 a3.ps a4.ps
[1] Wrote 1 pages
$  diff a3.ps a4.ps| head -18
--- a3.ps	2021-03-31 14:27:06.357527574 +0100
+++ a4.ps	2021-03-31 14:27:46.193636793 +0100
@@ -3,12 +3,12 @@
 %%For: Reuben Thomas
 %%Creator: a2ps version 4.14
 %%CreationDate: Wed Mar 31 14:27:06 2021
-%%BoundingBox: 24 24 818 1166
 %%DocumentData: Clean7Bit
 %%Orientation: Portrait
-%%Pages: 1
+%%DocumentMedia: plain 595 842 0 () ()
+%%BoundingBox: 0 0 595 842
+%%Pages: 1 0
 %%PageOrder: Ascend
-%%DocumentMedia: A3 842 1190 0 () ()
 %%DocumentNeededResources: font Courier
 %%+ font Courier-Bold
 %%+ font Courier-BoldOblique
```

Looks OK to me! Sorry, I don't have any idea what is going wrong with your example (unless it's that you didn't in fact use version 2.04 somehow?). In particular the `DocumentMedia` is set in the output, and the `BoundingBox` is changed by 2 points relative to the input, but it's set to the wrong paper size (input, not output).

**Comment by saumyakswain** [comment]
Sorry for bothering. In fact I had installed the psutils package at a non standard location and was invoking it as /path/to/psresize thinking it is portable. psresize was invoking the system version of psnup and not the compiled one which is not in path. Things work like a charm upon adding the install dir to $PATH.

**Comment by rrthomas** [comment]
Not at all, thanks for working out the problem. Psutils *should* be portable, so this is a bug, I've opened issue #33.
