### ISSUE TITLE
Issues in psutils man pages

### ISSUE THREAD

**Issue by hmartink** [rrthomas/psutils#39]
`Dear psutils maintainer,
the manpage-l10n project maintains a large number of translations of
man pages both from a large variety of sources (including psutils) as
well for a large variety of target languages.

During their work translators notice different possible issues in the
original (english) man pages. Sometimes this is a straightforward
typo, sometimes a hard to read sentence, sometimes this is a
convention not held up and sometimes we simply do not understand the
original.

We use several distributions as sources and update regularly (at
least every 2 month). This means we are fairly recent (some
distributions like archlinux also update frequently) but might miss
the latest upstream version once in a while, so the error might be
already fixed. We apologize and ask you to close the issue immediately
if this should be the case, but given the huge volume of projects and
the very limited number of volunteers we are not able to double check
each and every issue.

Secondly we translators see the manpages in the neutral po format,
i.e. converted and harmonized, but not the original source (be it man,
groff, xml or other). So we cannot provide a true patch (where
possible), but only an approximation which you need to convert into
your source format.

Finally the issues I'm reporting have accumulated over time and are
not always discovered by me, so sometimes my description of the
problem my be a bit limited - do not hesitate to ask so we can clarify
them.

I'm now reporting the errors for your project. If future reports
should use another channel, please let me know.

Man page: psbook.1
Issue: Usually bold commands use a lower case, even at the beginning of a sentence
"B<Psbook> uses B<Pstops> to rearrange pages from a PostScript document into "
"\\[oq]signatures\\[cq] for printing books or booklets, creating a new "
"PostScript file.  The signature size is the number of sides which will be "
"folded and bound together; the number given should be a multiple of four.  "
"Extra blank sides will be added if the file does not contain a multiple of "
"four pages."
--
Issue: I<-s> → B<-s>

"The I<-s> option selects the size of signature which will be used. The "
"signature size is the number of sides which will be folded and bound "
"together; the number given should be a multiple of four. The default is to "
"use one signature for the whole file. Extra blank sides will be added if the "
"file does not contain a multiple of four pages."
--
Issue: I<-q> → B<-q>

"Psbook normally prints the page numbers of the pages rearranged; the I<-q> "
"option suppresses this."
--
Issue 1: Missing B<> around names, e.g. pstops(1) → B<pstops>(1)
Issue 2: Remove psbook(1), see also to itself does not make sense

"psbook(1), psselect(1), pstops(1), epsffit(1), psnup(1), psresize(1), "
"psmerge(1), fixscribeps(1), getafm(1), fixdlsrps(1), fixfmps(1), "
"fixpsditps(1), fixpspps(1), fixtpps(1), fixwfwps(1), fixwpps(1), fixwwps(1), "
"extractres(1), includeres(1), showchar(1)"
`

**Comment by rrthomas** [comment]
Thanks for these. I had a look at the issues above, and the only issue I could find in the current man pages was incorrect use of capital letters in command names, which I have fixed. Closing now. I would be grateful if future bug reports could refer only to newer versions of psutils, i.e. 2.08 (yet to be released) and later.
