### ISSUE TITLE
Failing tests 2.08 release

### ISSUE THREAD

**Issue by opohorel** [rrthomas/psutils#40]
Hi, 

I wanted to update psutils to the newest release in Fedora, but I've run into multiple test failures when trying to build it.
Compared to 2.07 release, where there was 6 XFAIL tests, the 2.08 release has added 25 FAIL test on top.

Could you please look into this issue?

```
make  check-TESTS
make[1]: Entering directory '/builddir/build/BUILD/psutils-2.08'
make[2]: Entering directory '/builddir/build/BUILD/psutils-2.08'
PASS: tests/pstops-offsets.sh
PASS: tests/pstops-negative-offsets.sh
PASS: tests/pstops-multiple-pages.sh
XFAIL: tests/pstops-invalid-pagespecs.sh
FAIL: tests/pstops-multiple-turns-and-flips.sh
FAIL: tests/pstops-correct-angles.sh
PASS: tests/psbook-20.sh
PASS: tests/psbook-3.sh
PASS: tests/psbook-20-signature-4.sh
PASS: tests/psbook-3-signature-4.sh
XFAIL: tests/psbook-invalid-signature-size.sh
PASS: tests/psjoin-1-2-even.sh
PASS: tests/psjoin-1-2.sh
PASS: tests/psjoin-1-2-nostrip.sh
PASS: tests/psjoin-1-2-save.sh
FAIL: tests/psnup-20-2.sh
FAIL: tests/psnup-20-1.sh
FAIL: tests/psnup-20-4.sh
FAIL: tests/psnup-20-3.sh
FAIL: tests/psnup-20-1-inpaper-A5.sh
FAIL: tests/psnup-20-1-inpaper-A5-outpaper-A5.sh
FAIL: tests/psnup-20-1-inpaper-A4-outpaper-A5.sh
FAIL: tests/psnup-20-3-inpaper-A5.sh
FAIL: tests/psnup-20-2-inpaper-A5.sh
FAIL: tests/psnup-20-3-rotatedleft.sh
FAIL: tests/psnup-20-4-inpaper-A5.sh
FAIL: tests/psnup-20-1-flip.sh
FAIL: tests/psnup-20-3-rotatedright.sh
FAIL: tests/psnup-20-4-flip.sh
FAIL: tests/psnup-20-4-columnmajor.sh
PASS: tests/psnup-20-4-297mmx210mm.sh
FAIL: tests/psnup-20-4-border-20.sh
FAIL: tests/psnup-20-4-margin-10.sh
XFAIL: tests/psnup-20-4-impossible-margin.sh
XFAIL: tests/psnup-20-3-impossible-tolerance.sh
XFAIL: tests/psnup-20-4-impossible-border.sh
FAIL: tests/psresize-20-A5.sh
FAIL: tests/psresize-20-A3.sh
FAIL: tests/psresize-20-A4.sh
FAIL: tests/psresize-20-Letter.sh
FAIL: tests/psresize-20-A5in-A4.sh
FAIL: tests/psresize-20-A3in-A4.sh
PASS: tests/psselect-odd.sh
PASS: tests/psselect-reverse.sh
PASS: tests/psselect-even.sh
PASS: tests/psselect-positive-range.sh
PASS: tests/psselect-even-reverse.sh
PASS: tests/psselect-negative-range.sh
PASS: tests/psselect-positive-negative-range.sh
PASS: tests/psselect-individual-pages-and-dash-p.sh
XFAIL: tests/psselect-invalid-pagerange.sh
PASS: tests/psselect-options-and-complex-pagerange.sh
PASS: tests/epsffit.sh
PASS: tests/epsffit-rotate.sh
PASS: tests/epsffit-center.sh
PASS: tests/epsffit-aspect.sh
PASS: tests/epsffit-maximize.sh
PASS: tests/epsffit-rotate-aspect.sh
PASS: tests/epsffit-rotate-maximize.sh
PASS: tests/epsffit-center-rotate.sh
PASS: tests/epsffit-center-rotate-maximize.sh
PASS: tests/epsffit-center-rotate-aspect.sh
PASS: tests/epsffit-center-rotate-aspect-maximize.sh
PASS: tests/epsffit-showpage.sh
PASS: tests/extractres-and-includeres.sh
============================================================================
Testsuite summary for psutils 2.08
============================================================================
# TOTAL: 65
# PASS:  34
# SKIP:  0
# XFAIL: 6
# FAIL:  25
# XPASS: 0
# ERROR: 0
```

**Comment by rrthomas** [comment]
Sorry, this version of psutils requires an unreleased version of paper. There's no other change to psutils, so you're not missing out by not upgrading for now.

I shall have to get back to paper and make a release. I'll leave this issue open for now in case others stumble across this problem.

**Comment by rrthomas** [comment]
libpaper >= 1.20 is required. I released it shortly before 2.09!

**Comment by kloczek** [comment]
Looking on https://github.com/rrthomas/libpaper/tags it looks strange becasue 1.2 is not latest version.

**Comment by rrthomas** [comment]
Thanks, that's a very good point. The 2.x series are a dead end, so I shall remove them.

**Comment by rrthomas** [comment]
I've deleted the 2.x releases and tags.

**Comment by opohorel** [comment]
@rrthomas I have one follow-up question. What difference is between your libpaper fork, that you mention as a require, and libpaper that is provided by Debian?

**Comment by rrthomas** [comment]
@opohorel My libpaper is a continuation of the Debian version; the main change so far is an improved interface for user-level configuration: per-user paper sizes, and a simpler command for querying them.

**Comment by rrthomas** [comment]
> Does that mean psutils won't work with Debian paper?

That's right, it uses the new command-line interface (it's good for program users as well as human users!).

**Comment by opohorel** [comment]
> My libpaper is API-compatible with Debian's, and I'm working on getting it into Debian as an upgrade (i.e. really I'm just a new upstream maintainer).

Do you have a timeline for the new version release in Debian? Because I don't want to change upstream source of libpaper from Debian to your fork, if it is not necessary

**Comment by rrthomas** [comment]
> > My libpaper is API-compatible with Debian's, and I'm working on getting it into Debian as an upgrade (i.e. really I'm just a new upstream maintainer).
> 
> Do you have a timeline for the new version release in Debian? Because I don't want to change upstream source of libpaper from Debian to your fork, if it is not necessary

I thought you are packaging for Fedora? In which case, this GitHub project is the upstream. I am trying to get this version of libpaper packaged in Debian, not replace the old upstream location (whatever that is, I can't actually find any reference other than the original source tarball).

**Comment by opohorel** [comment]
> > > My libpaper is API-compatible with Debian's, and I'm working on getting it into Debian as an upgrade (i.e. really I'm just a new upstream maintainer).
> > 
> > 
> > Do you have a timeline for the new version release in Debian? Because I don't want to change upstream source of libpaper from Debian to your fork, if it is not necessary
> 
> I thought you are packaging for Fedora? In which case, this GitHub project is the upstream. I am trying to get this version of libpaper packaged in Debian, not replace the old upstream location (whatever that is, I can't actually find any reference other than the original source tarball).

libpaper was introduced to Fedora 16 years ago, [this](https://tracker.debian.org/pkg/libpaper) has been the upstream url from the start. Should we change the upstream url to your [fork](https://github.com/rrthomas/libpaper) or just wait until you get your changes to Debian repository? I would prefer the second option, as I'm not the maintainer of libpaper in Fedora.

**Comment by rrthomas** [comment]
> libpaper was introduced to Fedora 16 years ago, [this](https://tracker.debian.org/pkg/libpaper) has been the upstream url from the start. Should we change the upstream url to your [fork](https://github.com/rrthomas/libpaper) or just wait until you get your changes to Debian repository? I would prefer the second option, as I'm not the maintainer of libpaper in Fedora.

It would be better to change the URL: source code for new releases is on GitHub, and upstream issues should be filed there. My changes to the Debian package add a `Homepage` tag that reflects this.

**Comment by ppisar** [comment]
> I've deleted the 2.x releases and tags.

Do you talk about <https://github.com/rrthomas/libpaper/releases> repository? Because I can still see e.g. "Release v2.0.4" there. Also a master branch contains 2.0.4 code.

**Comment by rrthomas** [comment]
@ppisar since I wrote that comment I have made v2.x releases of libpaper. I deleted the old tags that referred to different versions of the "paper" project.
