### ISSUE TITLE
psnup fails due to paper command output (with hotfix)

### ISSUE THREAD

**Issue by 7eggert** [rrthomas/psutils#41]
First reported here: https://bugzilla.opensuse.org/show_bug.cgi?id=1202402

System:
OpenSuse Tumbleweed

Packages:
psutils-2.08-1.3.x86_64
paper-2.3-2.3.x86_64

When running psnup, /usr/share/psutils/PSUtils.pm will run `paper --unit=pt $paper_name` (Line 76)

It will expect a return value of / ([.0-9]+)x([.0-9]+) pt$/ (Line 77)

This (OpenSuse's) version of paper will output e.g. "A4" unless called with --size; then it will output "595.275590551181 841.889763779527" (which still can't be parsed)

Fixed function (sorry for not providing a patch):

/usr/share/psutils/PSUtils.pm
```
sub paper_size {
  my ($paper_name) = @_;
  chomp($paper_name = paper([])) unless defined($paper_name);
  my $dimensions = paper(["--unit=pt", "$paper_name"], 1) or return;
  my @match = $dimensions =~ / ([.0-9]+)x([.0-9]+) pt$/;
  if (!@match) {
    $dimensions = paper(["--unit=pt", "--size", "$paper_name"], 1);
    @match = $dimensions =~ /([.0-9]+) ([.0-9]+)$/;
  }
  my $old_locale = setlocale(LC_ALL);
  setlocale(LC_ALL, "");
  my ($w, $w_unparsed) = strtod($match[0]);
  my ($h, $h_unparsed) = strtod($match[1]);
  setlocale(LC_ALL, $old_locale);
  return int($w + 0.5), int($h + 0.5); # round dimensions to nearest point
}
```

**Comment by rrthomas** [comment]
Apologies for this incompatibility. The fix is to upgrade to the latest libpaper 1.2.2 (libpaper 1.2.x replaces paper 2.x).

Paper 2.4 (the last version of paper 2.x) also outputs the dimensions in the expected form.
