### ISSUE TITLE
3.0.8 release was not completed?

### ISSUE THREAD

**Issue by chenrui333** [rrthomas/psutils#56]
👋 it looks like 3.0.8 release was not completed, i.e. it did not get marked as latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137305

**Comment by rrthomas** [comment]
Apologies, indeed something went wrong in the middle and I manually completed the PyPI release but not the GitHub release. Done now.

**Comment by chenrui333** [comment]
Thanks @rrthomas!
