### ISSUE TITLE
`psnup` automatically adds a bottom margin?

### ISSUE THREAD

**Issue by traverseda** [rrthomas/psutils#6]
Trying to print a book, and no matter what settings I use I can't get rid of an half-inch-ish margin on the bottom of my pdf. It gets added during the psnup stage and messes up the formatting for the entire booklet, pushing the first few lines off the top of the page.

If there's any way to get around that, I'd appreciate it.

`pdf2ps Dark\ Wizard\ of\ Donkirk.pdf - | psbook -s32 | psnup -2 -pletter -s1 -b0 -m0 | ps2pdf - booklet.pdf`

[Dark Wizard of Donkirk.pdf](https://github.com/rrthomas/psutils/files/2907963/Dark.Wizard.of.Donkirk.pdf)

**Comment by rrthomas** [comment]
What version of psutils is this, please?

**Comment by traverseda** [comment]
The default that comes with archlinux, psutils 1.17-6.

`--version says`

>psbook release 1 patchlevel 17
>Copyright (C) Angus J. C. Duggan, 1991-1995. See file LICENSE for details.

Sorry if this isn't the right place, it's unclear how the ownership of all this works.

**Comment by rrthomas** [comment]
Not to worry, this is probably the best place there is. Can you possibly try the latest source release, 1.23?

**Comment by traverseda** [comment]
Yeah, I've got it compiled but it's saying `sh: paper: command not found`, I'll get it sorted out.

**Comment by traverseda** [comment]
Can confirm, I've fiddled with the settings a bit more but the same issue seems to be popping up.

`pdf2ps Dark\ Wizard\ of\ Donkirk.pdf - | psbook -s32 | ./psutils/psnup -2 -h21.59cm -w13.97cm -s1 -b0 -m0 -d | ps2pdf - booklet.pdf`

[booklet.pdf](https://github.com/rrthomas/psutils/files/2908033/booklet.pdf)

**Comment by rrthomas** [comment]
Thanks. I can reproduce this. The good news is that it doesn't happen with my personal version of psnup (it puts it to the bottom of the page). The bad news is that my personal version is not checked in, and is an intermediate state between my current development version (itself not in git yet) and the last release. I've been spending all my PS-wrangling time for the last couple of years actually making books, rather than fixing psutils. As far as I can see, my personal version just hackily sets the computed hshift and vshift to 0 (in other words, ignores them).

Of course, the shifting is deliberate: psnup is trying to centre its output. What are you actually expecting/hoping for?

**Comment by traverseda** [comment]
Well ultimately I'm hoping for a printable book that uses exactly the margins I set. My libreoffice template is set up so that each page should be exactly half the size of a letter page, and I'd like them to just show up side by side without resizing or moving around.

So the top left corner of page 1 is in the top left corner of the paper, and the top left corner of page 2 is 5.5 inches to the right of the top left corner of page 1.

If there's a simple override of the h/v shift I could set it and recompile, that would at least solve the problem for me in the sort term.

Thanks, it's pretty amazing to get this kind of response and support for a piece of software that's older than I am, and to see it so actively maintained.

**Comment by rrthomas** [comment]
OK, if you go with version 1.17, then add

    hshift = vshift = 0;

right before the comment "now construct specification list…". That should do it.

I'm now going to see if I can make some progress towards another release!

**Comment by rrthomas** [comment]
I think psnup needs to be told the input and output paper sizes. However, doing that with version 1.17 doesn't work, as the output paper size is the same as the input (despite `-pletter`).

**Comment by traverseda** [comment]
Thanks a bunch, I appreciate your taking the time to do this. If I knew perl at all I'd try to help out.

**Comment by rrthomas** [comment]
You're very welcome. No worries, this is not really hard, just something I have to plug on with (and write lots of tests for, because of the rewrite). I unexpectedly have a few free hours now, so I'll see if I can make some progress!

**Comment by traverseda** [comment]
I applied the same change to 1.23 and everything works exactly as I'd expect. Thanks again.

**Comment by rrthomas** [comment]
You're welcome. Git master head psnup is now working for me (two steps forward: I have made it work for me, rather than a hacked older version I was previously using; and I've committed changes that had languished on my machine for over a year).

There's more to do before another release, but at least public git is now what I"m using.

**Comment by traverseda** [comment]
That's pretty great. I notice that the version of psutils in archlinux is at 1.17, once you do another release let me know and I'll bother the package maintainers about it?

**Comment by traverseda** [comment]
I think as there were some significant bugs in 1.17 it shouldn't be too hard to get them on board, even if they see it as a new upstream. Would be easier if http://knackered.org/angus/psutils/ made some reference to other versions.

**Comment by rrthomas** [comment]
Indeed; Angus handed over to me years ago but unfortunately never updated his web site.
