### ISSUE TITLE
UserWarning: could not run `paper' command   warn(msg)

### ISSUE THREAD

**Issue by strikesmeasodd** [rrthomas/psutils#69]
When I try to run any of the psutils, it exits with this message:

```
warnings.py:28: UserWarning: could not run `paper' command
  warn(msg)
```

The message is the same for all of the utils and regardless of what arguments are included.

I have python 3.10 and installed psutils through pip. 

Please let me know if theres something I'm doing wrong

**Comment by rrthomas** [comment]
You need to install libpaper, as documented (but not sufficiently prominently, sorry!) in `README.md`. Since this is not a Python package, `pip` can't install it. Also, I thought one would get an error message at install time, but apparently not; I'll look into that.

**Comment by rrthomas** [comment]
Unfortunately it seems there's not a lot I can do about the test not running at install time.

I'll make a new release shortly with the documentation improvement (and it also fixes a bug to make the warning more readable).

**Comment by strikesmeasodd** [comment]
Thanks, installing libpaper got it working. I had assumed that was only required when installing from source, but it's clearer now with the documentation changes.
