### ISSUE TITLE
Test dependencies declared as normal build dependencies

### ISSUE THREAD

**Issue by jmairboeck** [rrthomas/psutils#71]
It seems the dependency on Wand that is declared here, isn't actually used:

https://github.com/rrthomas/psutils/blob/57e797fbdc0ba6327610fb535dcb7b1b4f01e2fb/pyproject.toml#L39

Can this be just removed?

**Comment by jmairboeck** [comment]
Ah, I see it used in tests, sorry. But it could be moved to test requirements instead (together with pytest-datafiles).

**Comment by rrthomas** [comment]
Thanks, done!
